In [1]:
import torch
import numpy as np

In [2]:
x = torch.Tensor(2, 3)          # An un-initialized Tensor object with size 2x3

print(x)                        # [torch.FloatTensor of size 2x3]

tensor([[1.3556e-19, 7.1463e+22, 4.6241e+30],
        [1.0552e+24, 1.9345e-19, 7.4086e+28]])


### Create a Tensor

In [3]:
v = torch.Tensor(2, 3)          # An un-initialized torch.FloatTensor of size 2x3
v

tensor([[-1.1600e-32,  4.5559e-41, -1.1600e-32],
        [ 4.5559e-41,  4.4842e-44,  0.0000e+00]])

In [4]:
v = torch.Tensor([[1,2],[4,5]]) # A Tensor initialized with a specific array
v

tensor([[1., 2.],
        [4., 5.]])

In [5]:
v = torch.LongTensor([1,2,3])   # A Tensor of type Long
v

tensor([1, 2, 3])

In [6]:
v = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
v

tensor([[0.0943, 0.0760, 0.2085],
        [0.9696, 0.4468, 0.5407]])

In [7]:
v = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
v

tensor([[-1.7860, -0.6709,  0.6969],
        [-0.1377,  0.0880, -0.8717]])

In [8]:
v = torch.randperm(4)           # Size 4. Random permutation of integers from 0 to 3
v

tensor([3, 0, 1, 2])

In [9]:
eye = torch.eye(3)              # Create an identity 3x3 tensor

In [10]:
v = torch.ones(10)              # A tensor of size 10 containing all ones
v

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
v = torch.ones(2, 1, 2, 1)      # Size 2x1x2x1
v

tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])

In [12]:
v = torch.ones_like(eye)        # A tensor with same shape as eye. Fill it with 1.
v

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
v = torch.zeros(10)             # A tensor of size 10 containing all zeros
v

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
v = torch.arange(5)             # similar to range(5) but creating a Tensor
v

tensor([0, 1, 2, 3, 4])

In [16]:
v = torch.arange(0, 5, step=1)  # Size 5. Similar to range(0, 5, 1)
v

tensor([0, 1, 2, 3, 4])

In [17]:
v = torch.linspace(1, 10, steps=10) # Create a Tensor with 10 linear points for (1, 10) inclusively
v

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
v = torch.logspace(start=-10, end=10, steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10
v

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [19]:
v = torch.ones(3, 3)
v

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
v[1].fill_(2)
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]])

In [21]:
v[2].fill_(3)
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])